# BitcoinMinerClean Configuration
#wallet = 15zwuwpXW1Hz8iTHEk8xfuWL8iJVMxthqF

mode = gpu                    # cpu or gpu (gpu later)
threads = 8                  # number of CPU threads (keep low for lottery mode)
throttle_ms = 3              # sleep milliseconds per hash attempt (higher = less CPU usage)
wallet = 15zwuwpXW1Hz8iTHEk8xfuWL8iJVMxthqF
worker = Ziggy.008
pool_url = stratum+tcp://solo.ckpool.org:3333   # optional for now

# Test / Lottery settings
test_mode = false              # if true, uses fixed easy header for testing
difficulty_bits = 24          # target difficulty (lower = easier for testing)